name: "Podcast Generator"
author: "Dan Mulupi"
description: "Tunajaribu"

runs:
  using: "docker"
  image: "Dockerfile"  # this is fine *only* if Dockerfile is in the same dir

branding:
  icon: "git-branch"
  color: "blue"

inputs:
  email:
    description: "The committer's email address"
    required: true
    default: "${{ github.actor }}@localhost"

  name:
    description: "The committer's name"
    required: true
    default: "${{ github.actor }}"
